### ISSUE TITLE
Feature Request: Ability to delete saved images.

### ISSUE THREAD

**Issue by DarioChan** [alievk/avatarify-python#413]
When I first installed this I ran a ton of tests and now the app won't open any new images and I have a bunch of junk images. How can I delete these other than attempting a reinstall?

**Comment by JohanAR** [comment]
First of all, are you really using Avatarify Python, and not the Windows app [Avatarify Desktop](https://github.com/alievk/avatarify-desktop)?

If it's really Avatarify Python, just delete the images you don't want from the "avatars" folder. The reason I'm asking which program you're running is because you also add new images by putting them in that folder, so it ought to be quite obvious how to remove them :)

**Comment by DarioChan** [comment]
Yes! I meant the Avatarify Desktop. Where would we go for that? Or does it also have a folder we can delete from?

**Comment by JohanAR** [comment]
I think it's supposed to be C:\Users\<yourname>\.avatarify\avatars\ but I'm not using Windows so I can't check

The link in my previous post goes to the Avatarify Desktop repository in case you need to report any bugs for it :)
