### ISSUE TITLE
Binary not enable 

### ISSUE THREAD

**Issue by James65780166666** [alievk/avatarify-python#495]
![IMG_20230110_175053_979](https://user-images.githubusercontent.com/122387645/211632824-82d493e9-826c-4ecd-80d7-f24ed762ac01.jpg)
**Describe the bug**

**To Reproduce**

**Info (please complete the following information):**
 - OS (e.g., Linux): 
 - GPU model: 

 - Any other relevant information: 

**Screenshots**

**Logs**

Please how do i go about this

**Comment by JohanAR** [comment]
Use the search function to find others who have had the same problem. The error is written on the last line (i.e. "invalid choice: 2020-resolver...")

And you should look up how to copy text from the terminal, and how to format it to make it readable on github. A photo of your monitor is not a valid issue report, partially because it makes it impossible to search in it.
