### ISSUE TITLE
Issue with run_windows.bat

### ISSUE THREAD

**Issue by manistar** [alievk/avatarify-python#524]
[**Describe](url) the bug**

**To Reproduce**

**Info (please complete the following information):**
 - OS (e.g., Linux): 
 - GPU model: 

 - Any other relevant information: 

**Screenshots**

**Logs**

![WhatsApp Image 2023-03-10 at 7 24 15 PM](https://user-images.githubusercontent.com/59540587/224395029-de3b6679-2f7d-4286-82a2-0c83108b12d1.jpeg)

Good day, please who have solution to this error, was able to solve the whole issue, but got this problem at the last stage, my internet and my external camera is connected.

Please share if you have any solution to this.

**Comment by manistar** [comment]
This code is working perfectly on other system without facing this error, but I don't know why this have to occur on Nvidia 3060

**Comment by JohanAR** [comment]
Looks like it could be some kind of network issue, though there is always the possibility of some local SSL library issue.

Can you copy the text from the terminal and paste it in the issue, so we can see the whole log? You also need to surround the text with code tags on github, otherwise the formatting gets weird.

**Comment by manistar** [comment]
Yes I have fixed this thanks.
