### ISSUE TITLE
Run_windows.bat not running

### ISSUE THREAD

**Issue by manistar** [alievk/avatarify-python#529]
**Describe the bug**

**To Reproduce**

**Info (please complete the following information):**
 - OS (e.g., Linux): 
 - GPU model: 

 - Any other relevant information: 

**Screenshots**

**Logs**

Please how do I fix this problem, I have been battling with it since morning.

`(avatarify) C:\Users\Admin\avatarify-python>run_windows.bat
[1678740966.718046] Loading Predictor
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 218, in <module>
    **predictor_args
  File "C:\Users\Admin\avatarify-python\afy\predictor_local.py", line 49, in _init_
    self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=True, device=self.device)
  File "C:\ProgramData\Miniconda3\envs\avatarify\lib\site-packages\face_alignment\api.py", line 83, in _init_
    load_file_from_url(models_urls.get(pytorch_version, default_model_urls)[network_name]))
  File "C:\ProgramData\Miniconda3\envs\avatarify\lib\site-packages\torch\jit\_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, f, map_location, _extra_files)
RuntimeError: [enforce fail at ..\caffe2\serialize\inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory
`

**Comment by JohanAR** [comment]
Never seen anyone having this issue before.. "failed finding central directory" sounds like it could be a network problem, or something failed during installation. Maybe try starting over in a clean directory, and run the install script again?

**Comment by manistar** [comment]
> Never seen anyone having this issue before.. "failed finding central directory" sounds like it could be a network problem, or something failed during installation. Maybe try starting over in a clean directory, and run the install script again?

This actually sorted it, it working fine now, thanks

**Comment by JohanAR** [comment]
Glad to hear! I'm closing the issue then. Feel free to re-open if it turns out that something wasn't working after all

**Comment by Noniboy1000** [comment]
base) C:\Users\USER\avatarify-python>run-windows.bat
'run-windows.bat' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\Users\USER\avatarify-python>run_windows.bat
Traceback (most recent call last):
  File "C:\Users\USER\miniconda3\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\Users\USER\miniconda3\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Users\USER\miniconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "afy/cam_fomm.py", line 8, in <module>
    import numpy as np
  File "C:\Users\USER\miniconda3\lib\site-packages\numpy\__init__.py", line 150, in <module>
    from . import core
  File "C:\Users\USER\miniconda3\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "C:\Users\USER\miniconda3\envs\avatarify\python.exe"
  * The NumPy version is: "1.21.6"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed: The specified module could not be found.

please possible solution

**Comment by JohanAR** [comment]
@Noniboy1000 not exactly the same issue, but I suspect the solution might be similar: Try installing again in a new location, and make sure you follow every step of the install instructions.
