### ISSUE TITLE
I have the solution to all avatarify-python problems

### ISSUE THREAD

**Issue by Kitopvibe1** [alievk/avatarify-python#551]
Hey guys, I'm kit
I know most of you must have heard of me lol

Avatarify is outdated which is making using it hard for y'all, but I have my personal solution I've been using for guys for months now cause I upgraded my avatarify.

I decided to post this today after seeing alot of comment and issues 😂

You can hit me up on WhatsApp, I'll login to your pc and set it up for you! I don't teach!!
`<link removed>`

**Comment by JohanAR** [comment]
If you know how to fix any of the current issues with avatarify-python you are free to submit a pull request, either with updated scripts or improved documentation. It might also be helpful to respond to any of the open issue reports with a solution.

However since I don't know you, I can't tell if you're just someone wanting to help people or if you're a scammer looking for victims.

Note to anyone else reading this: *Never* give remote access to your pc to random people on the internet. If a stranger approached you in the city, and asked for the keys to your house + your address, would you give it to them? I understand that a lot of people want to run avatarify but are struggling with it, but this a very big risk to take.

**Comment by Kitopvibe1** [comment]
Nope, not a scammer lol and loging in to someone's pc through TeamViewer is same as hacking pc as the person still have the control over his pc.

I decided to write that comment cause the way I helped my friends with avatarify worked out fine and the way you explained on GitHub or even YouTube is different from my method...

Sorry if my previous comment pissed you off tho

**Comment by JohanAR** [comment]
It's not pissing me off, sorry if it came across that way. However, as co-maintainer for the official avatarify project I do feel some kind of responsibility for what happens on this issue tracker. Maybe you're a friendly person who wants to help people, maybe you're a hacker, it's impossible for me to tell the difference. I only have your word for it.

Since you you have the following on your profile, I'm surprised that you're trying to downplay the risks of giving remote access of your computer to a stranger:

>  I’m interested in learning and improving my skills on phishing, Hacking, deep fakes and cyber security

Anyone with even basic knowledge about phishing, hacking and cyber security should know how bad it would be if a malicious party was allowed to connect to your pc using TeamViewer, AnyDesk, etc.

If you have a method to get avatarify-python running that is different from the official documentation, and you really want to help, then you could write down the steps here? Or maybe make a youtube video where you demonstrate it?

**Comment by davidlorex** [comment]
If you have solutions shear it here. Asking people to contact you privately is wrong.

**Comment by Kitopvibe1** [comment]
> If you have solutions shear it here. Asking people to contact you privately is wrong.

Dey play

**Comment by doomsday0965** [comment]
> > If you have solutions shear it here. Asking people to contact you privately is wrong.
> 
> Dey play

youre Nigerian? if you have a solution brother please help

**Comment by JohanAR** [comment]
@quviky1 that was my impression too, but I didn't want to immediately jump to conclusions.

**Comment by Kitopvibe1** [comment]
> His a scammer

yeah imma scammer cause i refused to drop the idea i'm using here lol

**Comment by Temitope2306** [comment]
Which one is the best between xpresion and avatarify
